### ISSUE TITLE
Duplicates In Statistics When Submitting Data

### ISSUE THREAD

**Issue by vegemike** [mrusse/Slsk-Upload-Stats-Tracker#11]
Hi again, sorry to create another issue so soon, but I just noticed that when data is submitted multiple times, although the stats do not change, both the folders and users list end up with duplicates (one extra for each time data is submitted)

![image_2024-05-30_001719160](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/assets/116464261/dc5b3d69-7bfb-4baf-a0d2-806a463b01f4)

![image_2024-05-30_001555438](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/assets/116464261/cd02049b-d46e-4f15-9906-fac891e8d9ae)
## (colours represent same user, also might be worth looking at the blank value for someone who made one tiny download)

![image_2024-05-30_001735728](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/assets/116464261/cf8b7cff-3143-459d-91c1-7125bbb46971)
## This occurs even when there's new users/downloads in the data, just as long as any part of it is duplicated from before. 
Not really a huge issue seeing as the numbers aren't wrong but just thought it was worth bringing up.

**Comment by mrusse** [comment]
Thanks for finding this!!! I should have found this for sure. Luckily it would fix itself with a relaunch which is probably why I missed it.

Fixed in this release: [https://github.com/mrusse/Slsk-Upload-Stats-Tracker/releases/tag/v2.1.4](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/releases/tag/v2.1.4)

Hope you enjoy the program (and hopefully I've fixed most of the bugs) 😄
